[build]
  publish = "public"
  command = "gatsby build"

[build.environment]
  NODE_VERSION = "19"
  NODE_OPTIONS = "--max_old_space_size=4096"


[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    x-frame-options = "ALLOW-FROM *"
    Content-Security-Policy = "frame-ancestors 'self' https://www.youtube.com https://youtu.be"
    Secure-Referrer-Policy = "origin-when-cross-origin"








